name: Cypress

on: [push]

jobs:
  main:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: |
          yarn install
        env:
          CI: true
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000